name: webroulette
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  roulette: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  js_interop: ^0.0.1
  json_annotation: ^4.9.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  hastebin_client:
    path: packages/hastebin_client

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations

workspace:
  - packages/hastebin_client
