include: package:lints/recommended.yaml

linter:
  rules:
    # Additional rules beyond the recommended set
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_const: true
    unnecessary_new: true
    sort_constructors_first: true
    sort_pub_dependencies: true