name: Format

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Runs on pull requests targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get    
    
      - name: Check formatting
        run: dart format --set-exit-if-changed --output=none .